os:
  - linux
dist:
  - xenial
language: node_js
node_js:
  - "10"
before_install:
  - sudo add-apt-repository ppa:longsleep/golang-backports -y
  - sudo apt-get update
  - sudo apt-get install -y golang-go
  - sudo apt-get install -y libev-dev
  - go env | grep GOPATH > gopath.env
  - source gopath.env 
  - export PATH=$PATH:$GOPATH/bin
  - go get -u github.com/tsenart/vegeta
  - npm install -g esy
install:
  - esy install -q
  - esy @libev install -q
before_script:
  - npm run build
jobs:
  include:
    - stage: "Test - Standard"
      script: /bin/bash ci/test-standard.sh
    - stage: "Test - Libev"
      if: branch = master
      script: /bin/bash ci/test-libev.sh
    - stage: "Load Test - Libev"
      if: branch = master
      script: /bin/bash ci/test-under-load.sh