os:
- linux
dist:
- xenial
language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- ssh-add ./deploy_key
- sudo add-apt-repository ppa:longsleep/golang-backports -y
- sudo apt-get update
- sudo apt-get install -y golang-go
- sudo apt-get install -y libev-dev
- go env | grep GOPATH > gopath.env
- source gopath.env
- export PATH=$PATH:$GOPATH/bin
- go get -u github.com/tsenart/vegeta
- npm install -g esy
install:
- esy install -q
- esy @libev install -q
before_script:
- npm run build
jobs:
  include:
  - stage: Test - Standard
    script: "/bin/bash ci/test-standard.sh"
  - stage: Test - Libev
    if: branch = master
    script: "/bin/bash ci/test-libev.sh"
  - stage: Load Test - Libev
    if: branch = master
    script: "/bin/bash ci/test-under-load.sh"
  - stage: Deploy Docs
    if: branch = master
    script: "/bin/bash ci/deploy-docs.sh"
